# Autogenerated wrapper script for autoconf_jll for i686-w64-mingw32
export autoconf

JLLWrappers.@generate_wrapper_header("autoconf")
JLLWrappers.@declare_file_product(autoconf)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        autoconf,
        "bin\\autoconf",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
